def end_game(board):
    board.is_checkmate()
    board.is_stalemate()
    board.outcome()
    board.can_claim_draw()
    board.can_claim_threefold_repetition()
    board.can_claim_fifty_moves()
    board.is_insufficient_material()
    board.is_fivefold_repetition()
    board.is_seventyfive_moves()